---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Dewansh Bhatt"
date: "September 18, 2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r}


```

```{r load-pkg-data}
#| message: false
library(Lahman)
library("tidyverse")
```

```{r}
library("usethis")

```

## Exercises

```{r}
usethis::use_git_config(
  user.name = "DewanshBhatt"
  , user.email = "dewanshbhatt@gmail.com"
)

```

```{r}
usethis::create_github_token()
```

```{r}
```

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

The `Teams` dataset has 3015 observations and 48 variables.

### Exercise 2

```{r}
mets <- Teams  |>
  dplyr::filter(teamID == "NYN")
my_mets <- mets |> 
  dplyr::filter(yearID>=2004 & yearID<=2012)
my_mets |> 
  dplyr::select(W,L,yearID,G)
```

### Exercise 3

```{r}

mets_ben <- Teams |>
  dplyr::select(teamID, yearID, RS=R, RA,G,W,L )|>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben

```

### Exercise 4

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = (1/(1+((RA/RS)^2))),WinPct = W/G,)
mets_ben

mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct*G)
mets_ben
```

### Exercise 5

```{r}
dplyr::filter(mets_ben,WPct>WinPct)
dplyr::filter(mets_ben,WPct<WinPct)



```

### Exercise 6

```{r}
dplyr::arrange(mets_ben, WinPct)

```

### Exercise 7

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(Diff = max(W_hat)-W_hat) |>
  dplyr::arrange(Diff)
```

### Exercise 8

```{r}
mets_ben |>
  dplyr::summarize(
    num_years = n_distinct(yearID), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = mean(WinPct),
    sum_resid = sum(Diff)
  )
```

### Exercise 10

```{r}
mets_ben <- mets_ben %>% 
  dplyr::mutate(gm = ifelse(yearID == 2004,"Jim Duquette", 
         ifelse(yearID >= 2005 & yearID <= 2010,"Omar Minaya","Sandy Alderson"
         )))
print(mets_ben)
```

### Exercise 11

```{r}
manager_summary <- mets_ben %>%
  group_by(gm) %>%
  dplyr::summarize(
    num_years = n(),
    total_W = sum(W),
    total_L = sum(L),
    total_WPct = mean(WPct),
    sum_resid = sum(Diff)
  )
```
```{r}
print(manager_summary)
```

